Ensure lib files are writable
When building I ran into the following error:
```
+ /usr/local/Cellar/qt/5.15.0/bin/macdeployqt 'Sonic Pi.app' /usr/local/Cellar/qt/5.15.0
ERROR: "error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't open input file: Sonic Pi.app/Contents/MacOS/libqscintilla2_qt5.15.0.0.dylib for writing (Permission denied)\nerror: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't lseek to offset: 0 in file: Sonic Pi.app/Contents/MacOS/libqscintilla2_qt5.15.0.0.dylib for writing (Bad file descriptor)\nerror: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't write new headers in file: Sonic Pi.app/Contents/MacOS/libqscintilla2_qt5.15.0.0.dylib (Bad file descriptor)\nerror: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't close written on input file: Sonic Pi.app/Contents/MacOS/libqscintilla2_qt5.15.0.0.dylib (Bad file descriptor)\n"
ERROR: ""
ERROR: "error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't open input file: Sonic Pi.app/Contents/MacOS/libqscintilla2_qt5.15.0.0.dylib for writing (Permission denied)\nerror: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't lseek to offset: 0 in file: Sonic Pi.app/Contents/MacOS/libqscintilla2_qt5.15.0.0.dylib for writing (Bad file descriptor)\nerror: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't write new headers in file: Sonic Pi.app/Contents/MacOS/libqscintilla2_qt5.15.0.0.dylib (Bad file descriptor)\nerror: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't close written on input file: Sonic Pi.app/Contents/MacOS/libqscintilla2_qt5.15.0.0.dylib (Bad file descriptor)\n"
ERROR: ""
...
```
It turned out that `libqscintilla2_qt5.15.0.0.dylib` was not writable, and modifying the permissions fixed it.